# frozen_string_literal: true

Bundler.require(:default, :development)

# This file was generated by the `rspec --init` command. Conventionally, all specs live
# under a `spec` directory, which RSpec adds to the `$LOAD_PATH`. The generated `.rspec`
# file contains `--require spec_helper` which will cause this file to always be loaded.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want. See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations configuration
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4.
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks configuration
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This will default to `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Run specs in random order to surface order dependencies.
  config.order = :random

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.

  # Allow more verbose output when running an individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output.
    config.default_formatter = 'doc'
  end
end

require 'active_model'
require 'postcode_validator'

def load_data(name)
  YAML.load_file("spec/data/#{name}.yml")
end

class TestModel
  include ActiveModel::Model
  attr_accessor :zipcode, :country
end
