name: Unit tests
on:
  push:
    branches: [main, next]
  pull_request:
    branches:  [main, next]
jobs:
  # Ruby unit tests
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1", "3.2"]
        gemfile: [dev/gemfiles/rails-6.1.x.gemfile, dev/gemfiles/rails-7.0.x.gemfile, Gemfile]
        exclude:
          # Exclude rubies < 2.7 for ActiveModel >= 7.0
          - ruby: "2.6"
            gemfile: dev/gemfiles/rails-7.0.x.gemfile
          - ruby: "2.6"
            gemfile: Gemfile
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
